select * from BJ204236.movimentacao_processo;

insert into BJ204236.movimentacao_processo (id_movimentacao, texto_despacho, num_processo, id_juiz)
    values (1234, '	Lorem ipsum odio sodales consequat dictum sagittis dolor ligula mi, pulvinar est ipsum porta hac purus phasellus fermentum, praesent at lobortis etiam orci amet malesuada luctus. aptent suspendisse per dictumst aenean vivamus lacinia sit senectus nostra, senectus amet imperdiet taciti ad magna aptent pretium arcu, leo aliquam blandit sodales malesuada enim per eleifend. augue cursus pellentesque laoreet risus est etiam adipiscing nunc etiam augue, nec metus euismod pulvinar elementum tincidunt quisque gravida conubia mollis viverra, lorem cursus taciti ad integer cubilia porta vulputate consectetur. commodo class nulla lacinia pulvinar porttitor risus condimentum curae et, at fusce proin habitant semper pulvinar nisl vel, ullamcorper torquent varius malesuada ut quis ad hendrerit ut, hac feugiat congue luctus aliquet arcu congue. 
	Vitae eget sed quis quisque duis dictumst accumsan vivamus purus, inceptos vitae eget tempor in nostra euismod aliquam mauris donec, mauris nibh porttitor magna iaculis scelerisque conubia justo. porttitor condimentum vestibulum leo laoreet imperdiet curabitur, morbi pharetra blandit eget aenean, non hendrerit consequat dui rhoncus. sit commodo vestibulum duis imperdiet porttitor est dolor elit nam, eget varius aliquet ultricies ipsum lectus dictumst habitasse, egestas blandit pharetra et suspendisse neque vehicula blandit. odio scelerisque dictum libero molestie sed varius, lobortis aliquet sociosqu primis. ', 
        '817258408mKl7216', 1);
        
insert into BJ204236.movimentacao_processo (id_movimentacao, texto_despacho, num_processo, id_juiz)
    values (2345, '	Lorem ipsum sociosqu curabitur etiam mi etiam, fermentum maecenas magna cubilia in, rutrum euismod vitae ac curae. etiam tristique hendrerit turpis conubia litora vivamus ut etiam vitae dapibus, erat sollicitudin cubilia donec suscipit velit pulvinar posuere luctus per, senectus sapien vestibulum per sem odio nostra a metus. cras ligula amet luctus ipsum primis duis litora congue vulputate, aenean libero quisque ut libero fames ullamcorper. eleifend donec dapibus mattis sodales, condimentum at ante ultrices habitasse, quisque lobortis sollicitudin. lectus lacinia hac et, hac. netus eget tincidunt volutpat aptent placerat etiam hac eu ultrices, aenean curae malesuada gravida convallis aenean vivamus pulvinar, curae placerat consectetur quam senectus netus pharetra aliquam. 
	Elit ut congue ipsum condimentum lorem scelerisque dictumst dolor semper sagittis, curae tellus neque velit venenatis felis pellentesque donec porta, lorem aptent nunc per nec fringilla ullamcorper nec suspendisse. maecenas nostra nullam posuere praesent neque nulla donec egestas sagittis ornare, ullamcorper aenean accumsan scelerisque consectetur phasellus molestie faucibus semper platea, aliquam aenean scelerisque bibendum risus phasellus dictum himenaeos donec. lorem integer duis egestas aliquet pulvinar turpis justo, vestibulum dapibus per tellus augue fusce, imperdiet blandit sociosqu mauris conubia tincidunt. scelerisque consequat vulputate eget maecenas fusce suspendisse magna, pharetra rutrum conubia diam congue.  ', 
        '30042428cGN88641', 2);
        
insert into BJ204236.movimentacao_processo (id_movimentacao, texto_despacho, num_processo, id_juiz)
    values (3456, '	Lorem ipsum congue sollicitudin ante velit vulputate blandit metus facilisis urna sagittis, turpis est mauris dictumst blandit imperdiet aenean eros quisque turpis, lectus proin fames fermentum ante rhoncus nunc fermentum netus elit. mollis nec sed eros urna etiam ante suscipit vitae, proin hendrerit rutrum potenti cursus purus odio erat, malesuada lacinia metus laoreet orci faucibus cursus. elit mi vitae potenti lacinia odio eleifend proin fermentum viverra neque mauris eros, ligula id potenti ullamcorper tristique aenean platea tellus sociosqu leo. inceptos at eu nostra magna primis ultricies odio eu, bibendum cubilia hendrerit venenatis lobortis quis aliquet ante, maecenas fringilla vitae massa nisl imperdiet magna. 
	Nisi congue viverra pulvinar cubilia eu faucibus enim pulvinar feugiat ad, arcu tellus sociosqu donec nisi arcu tempor cursus sapien, sodales arcu cubilia neque etiam pellentesque integer senectus non. turpis himenaeos rutrum in suspendisse eu quisque ac varius, habitasse et felis vel ut ultricies vestibulum dapibus odio, hac leo condimentum proin malesuada nec vitae. platea torquent pharetra sollicitudin odio metus porta habitant praesent placerat orci, condimentum tellus ultricies faucibus himenaeos ad venenatis viverra porta aliquet, eros rhoncus pulvinar tellus nulla torquent sapien habitasse vulputate. scelerisque ultricies habitasse ut nisl ad lacus nostra, tristique condimentum vivamus ultricies turpis.  ', 
        '5788038317142872', 3);
        
insert into BJ204236.movimentacao_processo (id_movimentacao, texto_despacho, num_processo, id_juiz)
    values (4567, '	Lorem ipsum etiam mi nibh tempus dictum porttitor commodo dolor, quis non eget suscipit habitasse arcu congue habitant velit cursus, vel ac arcu aliquam inceptos curabitur adipiscing blandit. id blandit velit lorem rutrum curabitur viverra arcu in felis, vel phasellus quisque non elementum dolor vitae commodo netus fringilla, curabitur ultrices posuere eros ligula curabitur sagittis viverra. arcu vulputate eget habitant a semper nec pharetra augue, vivamus sollicitudin at sapien porttitor ut imperdiet, elit arcu integer rutrum nunc maecenas mollis. lorem proin egestas nam bibendum felis nunc primis phasellus, justo cursus ut erat varius integer et feugiat phasellus, per ad vivamus aptent feugiat eros curabitur. 
	Luctus porta venenatis quisque nam bibendum mattis platea pulvinar libero urna etiam, lacus vehicula quam lectus sed cursus pulvinar pretium tincidunt integer, feugiat eros aenean diam feugiat ut venenatis etiam vivamus nisl. ornare porta purus libero velit cursus cras sociosqu suspendisse, conubia varius sapien risus nam sodales nunc vulputate, blandit faucibus ullamcorper ultrices purus mi dictumst. lacus scelerisque conubia cras consequat interdum cubilia suscipit, dapibus elit praesent nam ipsum quisque mi, interdum sociosqu sed faucibus vitae pulvinar. placerat non quis rutrum velit urna cubilia, suscipit donec suscipit etiam viverra maecenas sed, maecenas vehicula luctus nunc nisi.  ', 
        '532851587iOg2668', 4);
        
insert into BJ204236.movimentacao_processo (id_movimentacao, texto_despacho, num_processo, id_juiz)
    values (5678, '	Lorem ipsum cursus condimentum proin volutpat faucibus ultrices augue primis ultrices, aliquam nisl habitant mollis at sociosqu litora et netus. rutrum tellus ac ultrices torquent potenti scelerisque sociosqu sagittis, hendrerit eleifend tortor integer lectus tortor suspendisse hendrerit, aliquet fringilla sollicitudin ac proin aliquam donec. dictumst sem cubilia habitant suscipit etiam eu fermentum imperdiet aenean curabitur litora sem, vulputate egestas gravida platea tempus habitasse cras dui nam sociosqu congue, pretium molestie nullam pharetra sapien purus volutpat aenean fermentum curabitur adipiscing. urna in nisl amet magna lacinia lorem, cras curae vivamus purus torquent, donec cursus bibendum nullam consequat. 
	At dictum etiam faucibus bibendum maecenas porttitor torquent est pellentesque faucibus rutrum, posuere netus etiam mi porttitor nulla posuere iaculis nisi. ultrices posuere in nam accumsan eros leo nulla, suscipit ultrices elementum vestibulum fringilla tincidunt, aliquet ut ornare velit proin platea. cubilia rutrum porta leo elit vel leo etiam, morbi orci aenean laoreet eu elementum quisque fusce, lorem primis sociosqu aptent ante adipiscing. blandit nec feugiat per adipiscing felis quis aenean velit aliquet curabitur etiam, varius himenaeos blandit felis aliquam taciti tincidunt cubilia lectus curae turpis sit, vitae netus venenatis tincidunt taciti nec at fringilla ullamcorper aptent. 
	Tellus eu leo eleifend pharetra, est sodales. ', 
        '6848109107545oCq1817', 5);
        
commit;