INSERT INTO BJ204236.historico_adotante
    VALUES(1, 'Congue tempor elementum primis suscipit odio erat quam sapien orci fringilla id, luctus sapien dictum blandit turpis amet vitae diam sociosqu id. fermentum conubia sed est lacinia taciti ad mattis pharetra dictum, porta proin lacus curabitur ultricies risus ultrices ante id eros, nunc per nulla praesent duis sagittis nunc vivamus. venenatis eros a aenean scelerisque ultrices ultricies quam nisl nibh, class congue nam lacus aliquet senectus sagittis eleifend, nullam etiam ornare fames nostra tristique tempus bibendum. donec nisl metus vel ornare libero dolor metus, gravida donec scelerisque ante egestas vel pulvinar hendrerit, in ultrices rutrum odio morbi convallis. 
	Aliquam vulputate molestie sollicitudin sapien hac elit litora convallis suspendisse sollicitudin, lacus sem enim curabitur elementum duis ad velit lacinia, mollis egestas etiam turpis justo felis molestie dictum class. magna primis porttitor ac sollicitudin aenean, ipsum euismod amet a vulputate imperdiet, quisque fringilla sociosqu quis. curabitur nulla justo aliquam malesuada varius nisi vel fringilla pellentesque, sapien congue dolor feugiat euismod ut est taciti aenean, etiam enim semper pulvinar vel nunc habitant sollicitudin. nec libero egestas consectetur potenti morbi turpis himenaeos in urna leo cras rutrum sollicitudin, praesent per vulputate primis class vehicula ac odio habitasse nisi fringilla. 
	Habitasse scelerisque facilisis himenaeos, tincidunt. ',32826958020, 654821, 'RS');
    
INSERT INTO BJ204236.historico_adotante
    VALUES(2, 'Congue tempor elementum primis suscipit odio erat quam sapien orci fringilla id, luctus sapien dictum blandit turpis amet vitae diam sociosqu id. fermentum conubia sed est lacinia taciti ad mattis pharetra dictum, porta proin lacus curabitur ultricies risus ultrices ante id eros, nunc per nulla praesent duis sagittis nunc vivamus. venenatis eros a aenean scelerisque ultrices ultricies quam nisl nibh, class congue nam lacus aliquet senectus sagittis eleifend, nullam etiam ornare fames nostra tristique tempus bibendum. donec nisl metus vel ornare libero dolor metus, gravida donec scelerisque ante egestas vel pulvinar hendrerit, in ultrices rutrum odio morbi convallis. 
	Aliquam vulputate molestie sollicitudin sapien hac elit litora convallis suspendisse sollicitudin, lacus sem enim curabitur elementum duis ad velit lacinia, mollis egestas etiam turpis justo felis molestie dictum class. magna primis porttitor ac sollicitudin aenean, ipsum euismod amet a vulputate imperdiet, quisque fringilla sociosqu quis. curabitur nulla justo aliquam malesuada varius nisi vel fringilla pellentesque, sapien congue dolor feugiat euismod ut est taciti aenean, etiam enim semper pulvinar vel nunc habitant sollicitudin. nec libero egestas consectetur potenti morbi turpis himenaeos in urna leo cras rutrum sollicitudin, praesent per vulputate primis class vehicula ac odio habitasse nisi fringilla. 
	Habitasse scelerisque facilisis himenaeos, tincidunt. ',17813099060, 257356, 'RS');

INSERT INTO BJ204236.historico_adotante
    VALUES(3, 'Congue tempor elementum primis suscipit odio erat quam sapien orci fringilla id, luctus sapien dictum blandit turpis amet vitae diam sociosqu id. fermentum conubia sed est lacinia taciti ad mattis pharetra dictum, porta proin lacus curabitur ultricies risus ultrices ante id eros, nunc per nulla praesent duis sagittis nunc vivamus. venenatis eros a aenean scelerisque ultrices ultricies quam nisl nibh, class congue nam lacus aliquet senectus sagittis eleifend, nullam etiam ornare fames nostra tristique tempus bibendum. donec nisl metus vel ornare libero dolor metus, gravida donec scelerisque ante egestas vel pulvinar hendrerit, in ultrices rutrum odio morbi convallis. 
	Aliquam vulputate molestie sollicitudin sapien hac elit litora convallis suspendisse sollicitudin, lacus sem enim curabitur elementum duis ad velit lacinia, mollis egestas etiam turpis justo felis molestie dictum class. magna primis porttitor ac sollicitudin aenean, ipsum euismod amet a vulputate imperdiet, quisque fringilla sociosqu quis. curabitur nulla justo aliquam malesuada varius nisi vel fringilla pellentesque, sapien congue dolor feugiat euismod ut est taciti aenean, etiam enim semper pulvinar vel nunc habitant sollicitudin. nec libero egestas consectetur potenti morbi turpis himenaeos in urna leo cras rutrum sollicitudin, praesent per vulputate primis class vehicula ac odio habitasse nisi fringilla. 
	Habitasse scelerisque facilisis himenaeos, tincidunt. ',13367741000, 195934, 'PR');
    
INSERT INTO BJ204236.historico_adotante
    VALUES(4, '	Phasellus ornare eget mollis nam ultricies mauris urna, curabitur mollis molestie consectetur tellus ornare diam scelerisque, eget ullamcorper nec sagittis per sodales. posuere habitant dolor pulvinar donec rutrum maecenas ante nec id bibendum suspendisse, fusce rutrum molestie praesent auctor consectetur lacus curae cras condimentum, placerat tempus sollicitudin orci venenatis torquent vitae sapien maecenas dictum. elementum cursus sollicitudin donec sapien netus tristique, pretium bibendum pellentesque ipsum ultrices, gravida curabitur tempus cubilia nec. dictumst lectus risus nam placerat proin leo porttitor erat, metus nunc himenaeos urna inceptos laoreet massa sed, magna felis sollicitudin duis laoreet et cras. 
	Primis in volutpat risus mollis laoreet lectus in, arcu accumsan habitant hendrerit consectetur sem. curae suspendisse purus urna class suspendisse turpis egestas, ornare habitasse aliquet mollis odio potenti hac, etiam nunc suspendisse adipiscing leo velit. molestie sollicitudin convallis egestas ultricies pharetra nostra hac vitae augue gravida, viverra sit venenatis purus sit tortor lacus orci elit eleifend maecenas, sit volutpat sit feugiat primis nisl mauris mattis commodo. condimentum nulla etiam libero dolor fusce fames, id ornare enim quis eget dui, semper conubia id nullam nisi. aptent curabitur congue nibh tortor dapibus donec scelerisque, mauris praesent risus nisl blandit habitasse. 
	Nec metus etiam sociosqu leo, vitae aliquam. ',58833146006, 738291, 'RS');
    
INSERT INTO BJ204236.historico_adotante
    VALUES(5, 'Urna curabitur facilisis class luctus odio nullam lorem tempus odio euismod morbi, posuere class fusce condimentum quis cras sociosqu pulvinar conubia odio, pharetra amet fames accumsan in adipiscing feugiat enim fringilla praesent. curae senectus fermentum justo conubia aliquet consectetur gravida a aliquet netus lorem faucibus class, purus commodo erat tellus felis aenean gravida eros quam molestie leo mattis. blandit mauris etiam class nulla eu class scelerisque consectetur, in vestibulum nibh imperdiet aenean ullamcorper varius id lobortis, orci morbi dapibus consectetur tempus torquent eget. fames bibendum inceptos sapien cras venenatis per mattis aptent molestie risus, molestie lectus elit tristique tortor mi bibendum dapibus pretium, lectus arcu tristique non nostra libero rutrum curabitur mi. 
	Sollicitudin dui morbi quam quisque aenean class felis diam eros, quam leo aptent nulla aliquam arcu volutpat aenean nullam nostra, nulla ac fusce hac non diam ligula curabitur. turpis nullam quisque elit integer quisque amet ultricies quam tempor, magna platea mauris fringilla dictum nam senectus vehicula, in auctor aptent conubia id iaculis metus ornare. porttitor pharetra ac vulputate faucibus condimentum curae pellentesque felis, platea maecenas aliquam egestas maecenas aliquam ut quisque, nibh facilisis mollis ipsum egestas nisl ultrices. sit quisque nisl dictumst porta ut, quisque dictum habitant curae. ',
        62878465008, 202047, 'RJ');
        
INSERT INTO BJ204236.historico_adotante
    VALUES(6, '	Diam ullamcorper fusce suscipit etiam vulputate nisl leo magna, ut lacus arcu eros ornare facilisis aliquam eget, cras nullam varius feugiat mollis sociosqu aptent. id auctor augue senectus netus duis ultrices ornare sollicitudin sem, iaculis donec dapibus nisl torquent urna in rhoncus, pellentesque consectetur accumsan varius phasellus aptent volutpat pellentesque. a vulputate diam himenaeos vestibulum sem tempus, molestie praesent vulputate maecenas enim mattis ullamcorper, vitae curabitur vestibulum etiam tortor. adipiscing duis per hendrerit massa placerat donec quis euismod suscipit, hac lacus risus lacus suspendisse odio hac. malesuada blandit etiam tincidunt praesent quisque ipsum rhoncus dictum, himenaeos praesent etiam curabitur lectus eros augue tortor, semper nec molestie pellentesque turpis etiam dapibus. 
	Semper fusce cursus arcu vestibulum netus sed in suscipit, erat nulla sagittis odio metus feugiat ornare tempor nibh, etiam adipiscing aliquam id torquent vulputate duis. imperdiet praesent lobortis quisque cras libero ad orci fermentum feugiat, cras nibh suspendisse molestie platea hendrerit id dui ullamcorper urna, lectus felis enim pharetra vel purus interdum ornare. vestibulum nostra metus quam integer ante nisl, ligula ante massa platea pharetra ultrices metus, vel ultricies id aliquam libero. rutrum nibh ut bibendum eu quisque magna, tristique accumsan cras etiam quisque primis, aliquam lacinia metus quisque primis. ',
        79951754007, 666999, 'sp');
        
INSERT INTO BJ204236.historico_adotante
    VALUES(7, '	Luctus consequat orci malesuada mauris magna sit, blandit nisi est lacus vitae aenean rhoncus, ultrices aenean vehicula cursus curabitur. fermentum nibh condimentum quisque vitae elit sollicitudin, sem vitae non maecenas commodo donec, ante quam tellus dolor feugiat. tristique metus phasellus elementum odio per inceptos, tincidunt iaculis sem sagittis conubia, volutpat habitant diam neque leo. sollicitudin nullam hac congue dolor nec porttitor, volutpat tincidunt egestas hendrerit tempor, vivamus netus faucibus volutpat euismod. placerat phasellus primis sed leo scelerisque ipsum integer venenatis velit habitasse neque, molestie convallis bibendum phasellus vitae hac tortor metus pellentesque. 
	Hac torquent erat sodales auctor vulputate lorem ornare erat, molestie convallis morbi augue curabitur aptent tellus mauris, lorem scelerisque fringilla sit class fames nullam. sed ipsum mauris est malesuada eleifend molestie sodales habitasse, diam aptent sit nisi curae vel nec enim lectus, leo nam ac consequat sit duis ipsum. curae felis netus ullamcorper vestibulum ut nostra litora duis tincidunt, fringilla dictum maecenas dui nisl iaculis urna in. a vitae mi vel nostra nullam venenatis per, magna consectetur purus eleifend aliquet tempus iaculis, nec iaculis cubilia ipsum mollis primis. vivamus fringilla suspendisse aliquam senectus lorem orci ante, sagittis vitae porta lorem hendrerit tristique, sociosqu dapibus purus dictum posuere primis. ',
        05647413021, 321733, 'SC');
        
INSERT INTO BJ204236.historico_adotante
    VALUES(8, '	Fermentum himenaeos urna tempor sagittis pellentesque interdum hac sed porta primis ligula vitae augue pellentesque et, accumsan ad inceptos aenean eget ultricies erat ornare dui suscipit netus nec senectus inceptos. egestas donec sapien hendrerit tellus platea, velit ad imperdiet cras eros cursus, donec netus tempus amet. vulputate himenaeos tempor ullamcorper nunc bibendum enim vulputate eu hendrerit, sociosqu magna gravida quis bibendum viverra consequat congue enim, purus diam posuere fringilla bibendum mollis fermentum vulputate. risus faucibus sed pulvinar suspendisse inceptos sagittis auctor leo, imperdiet venenatis quisque auctor scelerisque mollis in scelerisque sollicitudin, cras etiam non id aliquet vel sagittis. 
	Hendrerit duis phasellus turpis porta imperdiet laoreet feugiat nec commodo diam, odio accumsan bibendum aliquet gravida neque etiam per donec, vivamus iaculis curae molestie taciti tortor nec donec semper. in aliquam ornare senectus fermentum placerat leo litora aenean primis himenaeos, convallis tellus nisi dolor duis aliquet lacinia sollicitudin mauris. vel vehicula fames nam nibh phasellus odio iaculis est, lacinia gravida porttitor sed eleifend metus arcu himenaeos pulvinar, litora accumsan commodo feugiat nisi vehicula tempor. fermentum cursus ut lacinia diam curabitur scelerisque ipsum lacus in, suscipit vulputate lobortis nec et hac quam dictum eu augue, morbi dolor primis lacinia erat felis posuere rhoncus. ',
        50443621071, 115719, 'BH');
        
INSERT INTO BJ204236.historico_adotante
    VALUES(9, '	Pretium nullam mi suscipit eget aliquam morbi donec nibh molestie, odio senectus etiam est felis diam fames rhoncus velit, lacus suspendisse volutpat eu molestie neque semper fringilla. congue nostra aliquam fusce eros etiam sodales ultrices vehicula donec, felis quis malesuada odio cursus eget aliquam id felis dui, donec fringilla nisi viverra bibendum dictum iaculis donec. cras malesuada magna ultrices orci donec blandit tellus senectus, mattis malesuada quis fusce maecenas aenean nullam venenatis, nunc class ac nec velit neque ut. placerat litora vehicula senectus habitasse sit sem imperdiet ligula sem aenean, inceptos cras et a rutrum aliquam lacus praesent vitae, etiam tellus sapien proin habitant tellus netus lacus sapien. 
	Est sit mattis phasellus imperdiet placerat phasellus praesent faucibus, ultrices sapien augue ipsum posuere porttitor purus, fames cras nisl curae malesuada suspendisse felis. varius taciti cursus rutrum viverra erat donec tempor eu mi fames neque, nec est cursus aenean faucibus felis est aenean enim mi euismod convallis, tellus lobortis dapibus urna accumsan curabitur libero nibh sagittis non. turpis donec faucibus tempus sapien magna, sagittis sit suspendisse porttitor molestie viverra, eros proin scelerisque cursus. amet dapibus facilisis semper posuere felis molestie, magna primis rutrum tellus quam aliquam luctus, diam risus facilisis curae eros. ',
        35383016031, 446820, 'RS');
        
INSERT INTO BJ204236.historico_adotante
    VALUES(10, ' Elit sem leo himenaeos placerat quisque aenean dui malesuada luctus justo euismod, viverra varius sit venenatis curae maecenas aenean elementum tempor mattis torquent, iaculis adipiscing curabitur fames maecenas aliquet accumsan lobortis duis dolor. quisque nam massa at elementum posuere inceptos eleifend a sed quam, arcu et ut senectus elit in nisl placerat pulvinar, commodo sit condimentum conubia fringilla nunc morbi ultrices ornare. habitasse tristique congue bibendum quisque libero torquent egestas nec etiam lobortis fusce netus placerat bibendum sem nullam, sem praesent primis turpis mi fringilla molestie consequat morbi mauris neque netus tempor ut. 
	Bibendum ut suscipit amet litora nibh proin, arcu accumsan ante eleifend nam, viverra feugiat metus eu vestibulum. pellentesque quam suspendisse non diam aliquam felis sollicitudin ullamcorper massa, neque senectus hendrerit et tempus habitant platea sodales non, ligula pharetra taciti per imperdiet pharetra fames netus. aliquam sed aliquet himenaeos sed etiam suscipit donec, porttitor interdum dui tempus at quisque, maecenas varius ipsum quisque cubilia ipsum. consectetur fusce aliquam eu pharetra lectus rutrum sollicitudin nec augue arcu, proin condimentum mi integer nibh consectetur posuere nisl vehicula odio, elit erat urna ultrices ornare lobortis massa curabitur fusce. 
	Et ante fermentum condimentum sagittis aenean ante laoreet, erat aenean interdum faucibus elementum. ',
        79939752040, 000175, 'SP');
    
select * from BJ204236.historico_adotante;
    
commit;
        
